# Generated by Django 3.1.2 on 2021-11-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modulo',
            fields=[
                ('idModulo', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreModulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipoLeccion',
            fields=[
                ('idTipoLeccion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipoLeccion', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('idRespuesta', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('fkUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuesta_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leccion',
            fields=[
                ('idLeccion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreLeccion', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fkRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.respuesta')),
                ('fkTipoLeccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.tipoleccion')),
            ],
        ),
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('idArchivo', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreArchivo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaEdicion', models.DateTimeField(auto_now_add=True)),
                ('fkUsuarioCreacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_usuario_creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
